services:
  rag_pipeline:
    build:
      context: ./rag_pipeline
    ports:
    - 3964:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - bot-tier
    command:
      [
        "uvicorn",
        "api:app",
        "--host",
        "0.0.0.0",
        "--workers",
        "1"
      ]

  telegram_bot:
    build:
      context: ./telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RAG_PIPELINE_URL=http://rag_pipeline:8000
    networks:
      - bot-tier
    command:
      [
        "python",
        "telegram_bot.py",
      ]

networks:
  bot-tier:
    driver: bridge
